# Generated by Django 2.2.7 on 2019-12-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titulo')),
                ('subtile', models.CharField(max_length=200, verbose_name='subtitulo')),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='services')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('upcreated', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
        ),
    ]
