# Generated by Django 2.2.7 on 2019-12-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='upcreated',
            new_name='updated',
        ),
    ]
